### PR TITLE
Topic/Reforge

### PR DESCRIPTION
**Pull request by gergondet**
Hi,

I've closed #19 to open this one as it has the same intent, make the scripts agnostic to the underlying CI tool, but the scripts have been rewritten to follow the approach of the build script (i.e. functions/"main" approach).

The changes included in this PR are the following

Major
--
1. Rewrite all scripts in a function/main fashion. This should make the inclusion of new CI tool or build platforms easier
2. Support for private git dependencies in the form of `user@host:/path/to/repo;branch` (where `;branch` is optionnal) This implies a major change for github dependencies as the separators between the repository name and the branch specifier has changed from `:` to `;`. This requires the builder to be able to clone using this address; this can be achieved using deploy keys in gitlab (or setting up a gitlab account for the builder), I am not sure how this could be done in travis but this sounds like a bad idea anyway (expose private code/ressources in a public environment)

Minor/Bug fixes
--
1. Fix the eigen dependencies script for 3.2.7
2. Add a script for pybindgen-0.16
3. If GH_PUSH_URI is set use it to push doc/notes
4. Do not update the doc if the gh-pages branch does not exist

Tested on travis and on gitlab-ci

### CODE REVIEW

**Comment by bchretien** [comment]
:+1: Really nice job!

Indeed, we will never pull private repositories from Travis builds.

For pybindgen, I don't know if the 0.17 version fixed a lot of bugs, but on Arch that's the one I'm using with Joris' patch applied (cf. [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-pybindgen)).

We can give it a go on RobOptim repositories, and if all looks well, we can merge.

**Comment by haudren** [comment]
:+1: Looks very nice !

Just a quick note on Pybindgen : last time I used it, it did not provide a default docstring... I had tried to make some changes ( https://bugs.launchpad.net/pybindgen/+bug/1381493 ) to auto-generate docstring, I do not know if this has been implemented since, but it could be a nice addition too. I will maybe try to submit a patch now that pybindgen is on GitHub (Hurray!)

**Comment by bchretien** [comment]
@haudren while we're at it, we should re-send @jorisv' patch too I guess.

**Comment by bchretien** [comment]
Doc upload [https://github.com/roboptim/roboptim-core/commit/a2b59751ba73e0e9b9bb626802cd5ccb48eb0ab2](successful) on roboptim-core.

**Pull request merged**
