### PR TITLE
Improve coverage reports and documentation update with GitLab

### PR DESCRIPTION
**Pull request by gergondet**
- Skip everything related to coveralls
- Upload coverage reports to the project wiki
- Upload documentation to the project wiki

To be evaluated/discussed:

All of this is done for a single branch and a single build, is it
enough? How to allow more knowing that wiki branches exist but are not
accesible through the web interface?

Coverage reports are kept for each commits and a page is created to
access all revisions' report. The rational is that it is interesting to
know whether or not your coverage evolved and coverage reports are
light.

Should we put coverage.info on the repository?

Documentation is strictly updated so only one revision is available at
anytime. The rational is that documentation is heavy and its history is
less interesting. For release documentation, the process can be done
manually by the developpers.

### CODE REVIEW

**Comment by bchretien** [comment]
:+1: Well done, and kudos for the updated README ;)

My 2 cents on the branch issue: documentation should not change based on compilers and preprocessor definitions, so ideally this should only be done for a unique main branch, and thus pushed to a single unique branch (e.g. `gh-pages` for GH projects). I think that there was actually a bug until now, with multiple builds pushing their (identical) doc to the same branch (we only checked for `gcc`). I guess we should only upload the doc when a given environment variable is set, and we then trust the user to set it on a single build.

As for the `coverage.info`, if the previous one is available, do we have an easy way to see/generate the diffs between successive versions? Coveralls highlights the files that were changed in the commit, and the differences in the respective metrics, such as number of lines or number of covered lines (cf. [this](https://coveralls.io/builds/4953614)). It may not be simple to achieve a similar result.

As for the documentation, this is the current approach, and it has worked pretty well for RobOptim. I squash the commits when releasing the libraries, and keep a copy of the current doc tagged with the release version (see [this](https://github.com/roboptim/roboptim-core/commits/gh-pages)). It could be made partially automatic with a script available in the jrl-cmakemodules I guess, but then again, people releasing versions and providing documentations are a minority ;) The doc branch takes a lot of storage space over time, maybe not as much now with SVG support, but it used to be a problem.

**Comment by gergondet** [comment]
> My 2 cents on the branch issue: documentation should not change based on compilers and preprocessor definitions, so ideally this should only be done for a unique main branch, and thus pushed to a single unique branch (e.g. gh-pages for GH projects). I think that there was actually a bug until now, with multiple builds pushing their (identical) doc to the same branch (we only checked for gcc). I guess we should only upload the doc when a given environment variable is set, and we then trust the user to set it on a single build.

That is what's happening for the documentation on GitLab. To trigger a documentation update, two things have to align:
- the branch must be either `master` or `CI_WIKI_BRANCH` if it is defined by the user
- in the build, the `CI_UPDATE_WIKI` must be set to `true`

> As for the coverage.info, if the previous one is available, do we have an easy way to see/generate the diffs between successive versions? Coveralls highlights the files that were changed in the commit, and the differences in the respective metrics, such as number of lines or number of covered lines (cf. this). It may not be simple to achieve a similar result.

I guess this is possible. I also guess this would be a lot of work...

> As for the documentation, this is the current approach, and it has worked pretty well for RobOptim. I squash the commits when releasing the libraries, and keep a copy of the current doc tagged with the release version (see this). It could be made partially automatic with a script available in the jrl-cmakemodules I guess, but then again, people releasing versions and providing documentations are a minority ;) The doc branch takes a lot of storage space over time, maybe not as much now with SVG support, but it used to be a problem.

To clarify, only one documentation version is on the wiki repository (the most up-to-date w.r.t the `CI_WIKI_BRANCH`). The eventual changes (not all commits will change the doc) are incremental so I think the wiki repo should not grow much. Of course as you said, it can be squashed upon release.

**Comment by gergondet** [comment]
bump

I am especially curious if this breaks coveralls support with github (shouldn't...)

**Comment by bchretien** [comment]
We can check on roboptim-core's travis branch if you want.

Btw I've had some issues with coveralls (it couldn't access publicly available code?!), so I [started using codecov.io](https://codecov.io/github/roboptim/roboptim-core) to see what it has to offer. It seems to be working fine as well (so far).

**Pull request merged**
