### PR TITLE
Improve AppVeyor interface

### PR DESCRIPTION
**Pull request by francois-keith**
- Add unit tests
- Compile in Debug

Note: 84d1393b0 removes the environment modification. This change of path removed the access to git.exe. This was a problem for calls to `git -describe`, required to have correct data in the pkg-config files.

### CODE REVIEW

**Comment by gergondet** [comment]
Hi Francois,

This looks good (especially the return code checking). However, as the comment indicates, putting the git folder in the path breaks project that use `cmake_add_fortran_subdirectory` because this puts the "wrong" sh in the path.

Can this be worked-around by providing the full git path to cmake rather than having the git directory in the path? (i.e. add `-DGIT=/path/to/git` to the cmake command)

**Comment by francois-keith** [comment]
:up: Passing the git via cmake [works](https://ci.appveyor.com/project/francois-keith/roboptim-core-plugin-eigen-tuqn0/build/3.2-dev-75)
Also, I corrected the choco install command : the confirmation is now mandatory, otherwise it freezes waiting for the user to confirm.

**Comment by gergondet** [comment]
Good job :smile_cat:

**Comment by bchretien** [comment]
:+1: Thanks François!

**Pull request merged**
